/*
  BOARD DATA ONLY
  Edit this file to curate the board. Do not edit script.js for content.
  All image paths are relative to this file and work on Neocities.
*/
window.BOARD_DATA = {
  language: { storageKey: 'archive-language', default: 'ru' },
  ui: {
    ru: { languageTitle: 'Выберите язык', languagePrompt: 'Перед входом на доску выберите язык архива.', zoom: 'масштаб', hint: 'тяните доску · scroll для масштаба', reset: 'сбросить вид', help: 'перетащите, чтобы осмотреть доску', helpCards: 'карточки открываются по клику', stamp: 'ОРИГИНАЛ', close: 'Закрыть рассказ', pageLink: 'открыть отдельную страницу ↗', openCard: 'Открыть улику', board: 'Интерактивная доска расследования', zoomOut: 'Уменьшить масштаб', zoomIn: 'Увеличить масштаб', author: 'Лев Орлов', story: 'рассказ' },
    en: { languageTitle: 'Choose a language', languagePrompt: 'Choose the archive language before entering the board.', zoom: 'zoom', hint: 'drag the board · scroll to zoom', reset: 'reset view', help: 'drag to inspect the board', helpCards: 'click cards to open them', stamp: 'ORIGINAL', close: 'Close story', pageLink: 'open separate page ↗', openCard: 'Open evidence', board: 'Interactive investigation board', zoomOut: 'Zoom out', zoomIn: 'Zoom in', author: 'Lev Orlov', story: 'story' }
  },
  board: { width: 1800, height: 1200, minZoom: .55, maxZoom: 1.55 },
  theme: {
    board: { color: '#243b37', texture: 'radial-gradient(rgba(201,190,151,.08) 1px, transparent 1.5px), radial-gradient(rgba(0,0,0,.25) 1px, transparent 1.4px), repeating-linear-gradient(112deg, rgba(255,255,255,.018) 0 2px, transparent 2px 9px)', image: '', size: '13px 13px, 19px 19px, 37px 37px' },
    reader: { background: '#d8d0bc', opacity: '.78', textColor: '#262720', accent: '#8c3028', width: 'min(900px, calc(100vw - 48px))' }
  },
  evidence: [
    { id: 'platform-9', material: 'polaroid', image: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 350"><rect width="500" height="350" fill="%2326312e"/><path d="M0 245 160 120l90 60 95-140 155 205v105H0Z" fill="%236d806f"/><path d="M300 80h16v220h-16z" fill="%23c49b65"/><circle cx="393" cy="70" r="30" fill="%23d8bd78"/></svg>', caption: { ru: 'Платформа №9', en: 'Platform 9' }, meta: { ru: 'дело «Последний поезд»', en: 'case “The Last Train”' }, x: 100, y: 170, width: 205, ratio: '4/3', rotation: -4, zIndex: 2, pin: true, href: { ru: 'stories/last-train.html', en: 'stories/last-train-en.html' } },
    { id: 'plain-window', material: 'image', frame: { preset: 'plain' }, image: { src: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 420 280"><rect width="420" height="280" fill="%23142120"/><rect x="60" y="35" width="250" height="210" fill="%23d2a45e" opacity=".8"/><rect x="80" y="55" width="210" height="170" fill="%231f3b3a"/><path d="M130 224V90h80v134" fill="%23443934"/><circle cx="355" cy="56" r="34" fill="%23e7d29b" opacity=".65"/></svg>' }, caption: 'Свет на третьем', meta: 'фото 08 / без рамки', x: 360, y: 250, width: 250, ratio: '3/2', rotation: 6, zIndex: 1, pin: true, href: 'stories/early-lights.html' },
    { id: 'framed-map', material: 'image', frame: { preset: 'photo-frame', style: { background: '#d8c4a0', padding: '12px', border: '1px solid #8b7650' } }, image: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 400"><rect width="400" height="400" fill="%23ddc88f"/><path d="M35 325 120 70l88 125 76-90 82 220" fill="none" stroke="%237b392f" stroke-width="8"/><circle cx="275" cy="188" r="18" fill="%23a33a2e"/><path d="M90 270h180M125 120h150" stroke="%232e4a43" stroke-width="3" stroke-dasharray="9 10"/></svg>', padding: 12, ratio: '1/1', caption: 'Карта маршрута', meta: 'рамка / архив 07', x: 675, y: 315, width: 210, rotation: -4, zIndex: 3, pin: true, href: 'stories/early-lights.html' },
    { id: 'receipt', material: 'clipping', text: 'ВЕЧЕРНИЕ НОВОСТИ\n\nДве чашки. Один человек. Время — 22:41. Официантка утверждает, что второй голос продолжал отвечать после ухода гостя.', caption: 'Чек из «Севера»', meta: 'найдено на обороте письма', x: 650, y: 85, width: 245, rotation: 3, zIndex: 3, pin: true, href: 'stories/north-cafe.html' },
    { id: 'blue-note', material: 'manuscript', text: 'Не ищи дверь.\n\nИщи того, кто однажды оставил её открытой.', caption: 'почерк Л.О.', meta: 'лист 04 / черновик', x: 940, y: 215, width: 190, rotation: 5, zIndex: 4, pin: true, href: 'stories/open-door.html' },
    { id: 'witness', material: 'manuscript', text: 'Она слышала море,\nхотя до моря было\nтриста километров.', caption: 'свидетельство 04', meta: 'голосовая запись / 00:48', x: 245, y: 555, width: 180, rotation: 2, zIndex: 2, pin: true, href: 'stories/sea-voice.html' },
    { id: 'map', material: 'clipping', text: 'КАРТА МАРШРУТА\n\nТам, где фонари загораются раньше, чем наступает вечер.', caption: 'точка исчезновения', meta: 'координаты зашифрованы', x: 1140, y: 640, width: 240, rotation: -3, zIndex: 2, pin: false, href: 'stories/early-lights.html' },
    { id: 'key', material: 'polaroid', image: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 350"><rect width="500" height="350" fill="%23766b58"/><path d="M100 250c0-90 80-150 160-80l100 80v50H100Z" fill="%23d5c08b"/><circle cx="260" cy="160" r="32" fill="none" stroke="%23453d31" stroke-width="16"/><path d="M278 181 405 300h-40l-20-24-22 24-26-27 25-26-18-18Z" fill="%23453d31"/></svg>', caption: 'Чужой ключ', meta: 'экспонат не опознан', x: 660, y: 545, width: '160px', height: '240px', aspectRatio: '2 / 3', fit: 'contain', objectPosition: 'center', framePadding: '10px', rotation: -6, zIndex: 5, pin: true, href: 'stories/strange-key.html' },
    { id: 'file-photo', material: 'image', frame: { preset: 'file' }, image: { src: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 260"><rect width="400" height="260" fill="%232f4c45"/><circle cx="300" cy="84" r="42" fill="%23c28a58"/><path d="M0 220 120 105l80 55 92-115 108 175v40H0Z" fill="%237d9a7c"/></svg>', fit: 'cover', objectPosition: 'center' }, caption: 'Файл наблюдения', meta: 'вложение / 11', x: 1110, y: 180, width: 220, height: 165, rotation: 3, zIndex: 4, pin: true, href: 'stories/early-lights.html' },
    { id: 'red-thread', material: 'marker', text: 'Смотреть сюда', caption: 'приоритет: высокий', meta: 'три совпадения', x: 1290, y: 105, width: 150, rotation: 4, zIndex: 4, pin: true },
    { id: 'tape-red', material: 'tape', text: 'НЕ ЗАБЫТЬ: спросить про фонарь', color: '#a33a2e', texture: 'fibers', x: 820, y: 35, width: 260, rotation: -3, zIndex: 8, pin: true, anchors: { bottom: [.5, 1], custom: [.82, .6] }, links: [{ to: 'receipt', fromAnchor: 'bottom', toAnchor: 'top', sag: 95 }, { to: 'blue-note', fromPoint: [.82, .6], toPoint: [.15, .08], sag: -62 }] },
    { id: 'label-ochre', material: 'label', text: 'АРХИВ 07 / НЕ ТРОГАТЬ', color: '#b18b4a', texture: 'grain', x: 1190, y: 345, width: 230, rotation: 5, zIndex: 6, pin: false },
    { id: 'postcard', material: 'cover', text: 'ОТКРЫТАЯ\nДВЕРЬ', caption: 'без обратного адреса', meta: 'открытка / 1987', x: 45, y: 780, width: 180, rotation: -5, zIndex: 2, pin: true, href: 'stories/open-door.html' },
    { id: 'voice', material: 'manuscript', text: '«Алло?»\n\nПауза. Три удара. Шум воды.', caption: 'расшифровка', meta: 'кассета B / фрагмент', x: 920, y: 470, width: 185, rotation: -2, zIndex: 3, pin: true, href: 'stories/sea-voice.html' },
    { id: 'matchbook', material: 'marker', text: '№ 13', caption: 'спичечный коробок', meta: 'гостиница «Маяк»', x: 1400, y: 490, width: 150, rotation: -6, zIndex: 4, pin: true, href: 'stories/strange-key.html' },
    { id: 'newspaper', material: 'clipping', text: 'ЧЕЛОВЕК БЕЗ ТЕНИ\n\nСвидетели уверяют: он вошёл, но не вышел.', caption: 'вечерний выпуск', meta: 'газета / стр. 6', x: 1360, y: 760, width: 255, rotation: 2, zIndex: 2, pin: false, href: 'stories/last-train.html' },
    { id: 'long-clipping', material: 'clipping', text: 'АРХИВНОЕ СООБЩЕНИЕ\n\nВ 03:17 на северной платформе нашли билет без пункта назначения. На обороте было написано только одно имя. Бумага пахла дождём и дымом.', caption: 'длинная вырезка', meta: 'архив / лист 12', x: 490, y: 820, width: 275, rotation: -2, zIndex: 1, pin: true, href: 'stories/last-train.html' },
    { id: 'cover', material: 'cover', text: 'ПОСЛЕДНИЙ\nПОЕЗД', caption: 'обложка рассказа', meta: 'Лев Орлов', x: 1050, y: 790, width: 190, rotation: 7, zIndex: 3, pin: true, href: 'stories/last-train.html', reader: 'page' },
    { id: 'panel-story', material: 'tape', text: { ru: 'ОТКРЫТЬ ДЕЛО', en: 'OPEN THE CASE' }, color: '#d4bd77', texture: 'paper', x: 330, y: 980, width: 220, rotation: 2, zIndex: 7, pin: true, href: { ru: 'stories/open-door.html', en: 'stories/open-door-en.html' }, reader: 'panel', readerTitle: { ru: 'Открытая дверь', en: 'The Open Door' }, readerByline: { ru: 'Лев Орлов · дело № 07 / рассказ 03', en: 'Lev Orlov · case 07 / story 03' }, readerCover: { image: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 360"><rect width="800" height="360" fill="%231d3631"/><circle cx="625" cy="92" r="54" fill="%23bd6a4a"/><path d="M210 360V90h270v270" fill="%23c4a46b"/><path d="M260 360V150h170v210" fill="%23172827"/><path d="M0 320 150 220l100 60 130-120 420 160v40H0Z" fill="%233f6256"/></svg>', width: '100%', height: '220px', fit: 'cover', objectPosition: 'center' }, readerBody: { ru: 'Дом стоял на месте, но за ним больше ничего не было. Ни улицы, ни двора, ни соседского окна. Только лестница, ведущая вниз, хотя под домом не было подвала.\n\nОн вошёл, потому что на ручке остался тёплый след.', en: 'The house stood in its place, but there was nothing behind it. No street, yard, or neighbour’s window. Only a staircase leading down, though there was no basement.\n\nHe entered because the handle still held a warm trace.' } }
  ],
  links: [
    { from: 'platform-9', to: 'receipt', fromAnchor: 'right', toAnchor: 'left', sag: 86 }, { from: 'plain-window', to: 'framed-map', fromAnchor: 'left', toAnchor: 'top', sag: -64 }, { from: 'framed-map', to: 'map', fromPoint: [.98, .5], toPoint: [.5, .02], sag: 72 }, ['receipt', 'blue-note'], ['platform-9', 'witness'], ['witness', 'key'], ['key', 'map'], ['blue-note', 'map'], ['receipt', 'red-thread'], ['red-thread', 'voice'], ['voice', 'map'], ['witness', 'postcard'], ['postcard', 'long-clipping'], ['long-clipping', 'cover'], ['key', 'matchbook'], ['matchbook', 'newspaper'], ['map', 'newspaper'], ['blue-note', 'voice'], ['cover', 'newspaper']
  ]
};
